import { ErrorBoundary } from '@/components/ErrorBoundary';
import { Footer } from '@/components/Footer';
import Header from '@/components/Header';
import { AuthProvider } from '@/contexts/AuthContext/AuthContext';
import { locales } from '@/navigation';
import { responsiveFontSizesTheme } from '@/theme';
import { ThemeProvider } from '@mui/material';
import type { Metadata } from 'next';
import { NextIntlClientProvider, useMessages } from 'next-intl';
import { Inter } from 'next/font/google';
import { notFound } from 'next/navigation';

import './globals.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'GraphiQL App',
  description: 'Generated by create Next GraphiQL app',
};

export default function RootLayout({
  children,
  params: { locale },
}: Readonly<{
  children: React.ReactNode;
  params: {
    locale: string;
  };
}>) {
  if (!locales.includes(locale)) {
    notFound();
  }
  const messages = useMessages();

  return (
    <html lang={locale}>
      <NextIntlClientProvider locale={locale} messages={messages}>
        <ThemeProvider theme={responsiveFontSizesTheme}>
          <body className={inter.className}>
            <ErrorBoundary>
              <AuthProvider>
                <Header />
                <main className='main'>{children}</main>
                <Footer />
              </AuthProvider>
            </ErrorBoundary>
          </body>
        </ThemeProvider>
      </NextIntlClientProvider>
    </html>
  );
}
